eureka:
  client:
  #this client should register to the server -i.e the url given below
   service-url:
    defaultZone: http://localhost:8761/eureka/
microservice:
 payment-service:
  endpoints:
   getPaymentById: 
    uri: http://PAYMENT-SERVICE/payments/
 user-service:
  endpoints:
   getUserById: 
    uri: http://USER-SERVICE/users/
test:
 input: 344444444
logging:
 file:
  name: E:\MIU\MSD\Career_startegy\revsion\Java\microservice\MicroserviceClass\app-logs\ecom-app.log 
